version: '3.3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_ticket_development
    volumes:
      - promo-mysql:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'

volumes:
  promo-mysql:
